language: go

go:
 - 1.9
 - "1.10"

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - go get -u github.com/modocache/gover
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell
  - dep ensure

script:
  - golint -set_exit_status ./shodan/...
  - ineffassign ./shodan/
  - misspell -error README.md ./shodan/**/*
  - gofmt -l shodan/ | read && echo "Code differs from gofmt's style" 1>&2 && exit 1 || true
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./shodan/

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
